config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :chatrooms, only: [:show, :index, :destroy] do
    resources :messages, only: [:create, :destroy, :index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'dashboard', to: 'pages#dashboard'
  get 'home', to: 'pages#home'
  get 'documents', to: 'pages#documents'
  get 'results', to: 'results#index'

  resources :courses do
    resources :sessions
  end
  resources :results

  resources :student_courses, only: [ :edit, :update ]

  resources :results
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users, dependent: :destroy
  has_many :users, through: :chatroom_users
  has_many :messages, dependent: :destroy
  # has_many_attached :attachments, dependent: :destroy
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
    @users = User.all
  end

  def show
    @chatroom = Chatroom.includes(:messages).find(params[:id])
    @message = Message.new
    @messages = @chatroom.messages
    @chatroom_users = ChatroomUser.where(chatroom_id: @chatroom.id)
    @chatrooms = Chatroom.all
  end

  # private

  # def chatroom_params
  #   params.require(:chatroom).permit(:content, :body, attachments: [])
  # end
end

app/views/chatrooms/index.html.erb
<div class="chatchat">


   <div class="menu4">
      <p class="wel">Welcome <br> <span class="user"><%= current_user.nickname %></span> </p>
        <hr>

      <div class="today">
        <br>
      <%=  image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/v1664917228/Studeasy/Sans_titre_80_n5hekv.png", width:"100px"%>
        <p> <% @date= Date.today %> <%= @date.strftime('%a %d %B %Y') %></p>
      </div>
        <br>
        <hr>


      <%= link_to "Courses", courses_path, class:"btncourses" %>
        <hr>
      <%=  link_to "Documents", documents_path, class:"btndoc" %>
        <hr>
      <%= link_to "Results", results_path, class:'btnresults' %>
        <hr>
      <%= link_to "Chat", chatrooms_path, id:"btnchat" %>
        <hr>
      <%= link_to "Home", dashboard_path, id:"btndash" %>

  </div>


  <div class="study">
    <p class="classs">The Pythagor University - class Maths L2</p>
    <p class="usermail"><%= current_user.email %> </p>
  </div>



    <div class="chatindex">
      <% @chatrooms.each do |chatroom| %>
        <div class="classroom">
          <h5><%= chatroom.name %></h5>
          <%= link_to chatroom_path(chatroom) do %>
            <br>
            <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1665142364/Studeasy/Sans_titre_99_qi2g9s.png' , width:'90px'%>
          <% end %>


        </div>
      <% end %>
    </div>

    <div class="classmates">
      <div class="upmate">
      <br>
        Online classmates
      </div>

      <% @users.each do |user| %>
        <div class="mates">
          <%= user.nickname  %>

        </div>

      <% end %>
    </div>



</div>

app/views/chatrooms/show.html.erb
<div class="container-users-and-chat" >

  <div class="classmate-table">
    <table>
    <thead>
      <tr>
        <th><h2>Total students in this class : <%= @chatroom_users.count%></h2></th>
      </tr>
    </thead>

    <tbody>
    <% @chatroom_users.each do |chatroom_user| %>
      <tr>
        <td class="classmate"><i class="fa-solid fa-user-tie"></i> <p><%= chatroom_user.user.email %></p></td>
        <% end %>
      </tr>
      <tr>
        <td></td>
      </tr>
    </tbody>
    </table>
  <div class="chatroom-button">
    <%= link_to "Other chatrooms", chatrooms_path %>
  </div>
  </div>



  <div class="container chatroom"
    data-controller="chatroom-subscription"
    data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
    data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">

    <div class="messages" data-chatroom-subscription-target="messages">
      <% @chatroom.messages.each do |message| %>
          <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
            <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
              <%= render "messages/message", message: message %>
            </div>
          </div>
      <% end %>
    </div>



  <%= simple_form_for [@chatroom, @message], remote: true,
   html: {data: {action: "ajax:success->chatroom-subscription#resetForm"}, class: "d-flex" } do |f| %>
    <%= f.input :content, label: false, placeholder: "Send a message for the #{@chatroom.name} channel", wrapper_html: {class: "flex-grow-1"} %>
    <%#= link_to f.input :attachments, as: :file, input_html: { multiple: true }, class: "attachement-image", title: "" do %>
      <%#= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1665147769/Studeasy/Sans_titre_100_ezewru.png', width:"30px" %>
    <%# end %>
     <%= f.input :attachments, as: :file, input_html: { multiple: true }, class: "attachement-image" , title: "" %>



    <%# La ligne au dessus créé ce bousin en dessous -----> %>
    <%# <div class="mb-3 file optional message_attachments">
      <label class="form-label file optional" for="message_attachments">Attachments</label>
      <input class="form-control file optional" multiple="multiple" type="file" name="message[attachments][]" id="message_attachments">
    </div> %>


    <%# <%= f.submit "Send", class: "btn btn-primary"  %>
    <%# Remplacé par les lignes suivantes pour juste foutre un logo %>
    <%= button_tag type: 'submit', class: "button my-button", id: "sending-button" do %>
      <i class="fa-solid fa-arrow-right" aria-hidden="true"></i>
    <% end %>

  <% end %>



</div>

<div>