config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :chatrooms, only: [:show, :index, :destroy] do
    resources :messages, only: [:create, :destroy, :index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'dashboard', to: 'pages#dashboard'
  get 'home', to: 'pages#home'
  get 'documents', to: 'pages#documents'
  get 'results', to: 'results#index'

  resources :courses do
    resources :sessions
  end
  resources :results

  resources :student_courses, only: [ :edit, :update ]

  resources :results
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to home_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dhxefoe7j/image/upload/v1662821983/Studeasy/pool_3_ff7ubx.png" %>
  <% end %>




  <%# <h1 class="title">
          <span class ="s">S</span>
          <span class ="t">t</span>
          <span class ="u">u</span>
          <span class ="d">d</span>
          <span class ="i">i</span>
          <span class ="z">z</span>
          <span class ="y">y</span>
        </h1> %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Edit profile", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "out" %>
        </li>
        <li class="nav-item dropdown">
          <%# <%= current_user.email %>
          <%= image_tag "https://res.cloudinary.com/dhxefoe7j/image/upload/v1662822324/Studeasy/pool_5_x2g1qx.png", width: "70px", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <%# <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%# <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <%# </div> %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="trame">
  <div class="sidebar">
    <% if user_signed_in? %>
      <p class="wel">Welcome <span class="user"><%= current_user.email %></span> </p>
    <% end %>
        <hr>

      <div class="today">
        <br>
      <%=  image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/o_55/v1663708205/Studeasy/Sans_titre_46_wq4lgq.png", width:"90px"%>
        <p> <% @date= Date.today %> <%= @date.strftime('%a %d %B %Y') %></p>
      </div>
        <br>
        <hr>


      <%= link_to "Courses", courses_path, class:"btncourses" %>
        <hr>
      <%=  link_to "Documents", documents_path, class:"btndoc" %>
        <hr>
      <%= link_to "Results", results_path, class:'btnresults' %>
        <hr>
      <%= link_to "Chat", chatrooms_path, class:"btnchat" %>
        <hr>
        <br>
        <br>
        <br>
  </div>
</div>