config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :chatrooms, only: [:show, :index, :destroy] do
    resources :messages, only: [:create, :destroy, :index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'dashboard', to: 'pages#dashboard'
  get 'home', to: 'pages#home'
  get 'documents', to: 'pages#documents'
  get 'results', to: 'results#index'

  resources :courses do
    resources :sessions
  end
  resources :results

  resources :student_courses, only: [ :edit, :update ]

  resources :results
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
    @users = User.all
  end

  def show
    @user = current_user
    @course = Course.find(params[:id])
    @sessions = Session.where(course_id: @course.id)
  end

  def update
    @user = current_user
    @student_course = Course.find(params[:id])

    if @student_course.update(student_course_params_update)
      redirect_to course_path(@student_course.id)
    else
      render :edit
    end
  end

  private

  def student_course_params_update
    params.permit(:file)
  end
end

app/views/courses/index.html.erb
<div class="coursesindex">

  <div class="upcourses">
    <%# <h1 class ="titlecourses">Your courses</h1> %>
    <p><b>Maths Sup L2 </b>- Pythagor University</p>
  </div>

  <div class="container1">
    <div class="menu3">
        <p class="wel">Welcome <br> <span class="user"><%= current_user.nickname %></span> </p>
          <hr>

        <div class="today">
          <br>
        <%=  image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/v1664917228/Studeasy/Sans_titre_80_n5hekv.png", width:"100px"%>
          <p> <% @date= Date.today %> <%= @date.strftime('%a %d %B %Y') %></p>
        </div>
          <br>
          <hr>


        <%= link_to "Courses", courses_path, class:"btncourses" %>
          <hr>
        <%=  link_to "Documents", documents_path, class:"btndoc" %>
          <hr>
        <%= link_to "Results", results_path, class:'btnresults' %>
          <hr>
        <%= link_to "Chat", chatrooms_path, id:"btnchat" %>
          <hr>
        <%= link_to "Home", dashboard_path, id:"btndash" %>
          <br>
          <br>
          <br>
      </div>

    <div class= "result">
        <% @courses.each do |course| %>
            <div class="card-course">
            <%= cl_image_tag course.photo.key %>
                <div class="card-course-infos">
                    <h2> <%= course.title %></h2>
                    <p> <%= course.description %></p>
                    <%# <p> Created by Professor (user_id) <%= course.user_id %>
                    <%# <p>Teacher ? <%= current_user.teacher? %>
                    <br>
                    <%= link_to "View course", course_path(course.id), class: "btn btn-flat" %>
                </div>
            </div>
        <% end %>
    </div>

    <div class="buddies">

      <div class="faces">
        <div class="bud">
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_white/v1661857073/Nanny%20N%20Kids/profile4_bs5yu6.jpg', width:'55px' %>
          <p> Laura Peterson</p>
        </div>
        <div class="bud">
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_white/v1661771495/Nanny%20N%20Kids/avatar_Ophe_uar2wv.jpg', width:'55px' %>
          <p> Ophe Nguyen</p>
        </div>
        <div class="bud">
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_white/v1661857073/Nanny%20N%20Kids/profile3_crt6jn.jpg', width:'55px' %>
          <p>Johana Williams</p>
        </div>
        <div class="bud">
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_white/v1661857073/Nanny%20N%20Kids/profile2_dbkayh.jpg', width:'55px' %>
          <p>Jennifer Ross</p>
        </div>
        <div class="bud">
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_white/v1661857074/Nanny%20N%20Kids/profile1_jfyqn5.jpg', width:'55px' %>
          <p>Peter White</p>
        </div>
        <div class="bud">
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_white/v1665090635/Studeasy/Sans_titre_89_qehzjs.png', width:'55px' %>
          <p>Andrew Smith </p>
        </div>
        <div class="bud">
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_white/v1665090737/Studeasy/Sans_titre_93_howkhj.png', width:'55px' %>
          <p>Mickael Evans</p>
        </div>
        <div class="bud">
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_white/v1665090737/Studeasy/Sans_titre_92_fmpz1c.png', width:'55px' %>
          <p>Tommy Pierce</p>
        </div>
        <div class="bud">
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_white/v1665090737/Studeasy/Sans_titre_94_ypor7q.png', width:'55px' %>
          <p>John Pirelli</p>
        </div>
        <div class="bud">
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_white/v1665090798/Studeasy/Sans_titre_96_sazq9u.png', width:'55px' %>
          <p>Andrea Clifford</p>
        </div>

      </div>

      <div class="purplebud">
        <p>Class buddies</p>
        <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1665094982/Studeasy/Sans_titre_98_mkqgq9.png', width:'80' %>
      </div>
    </div>


  </div>

</div>

app/views/courses/show.html.erb
<div class="docbox">

  <div class="doctitle">
    <div class="upsession">
      <h1><%= @course.title %></h1>
      <div class="desc">
        <h5><%= @course.description %></h5>
      </div>
    </div>

    <div class="searching-course">
      <input type="search" id="research" name="searchQuery" placeholder="Search for documents...">
    </div>






  </div>



  <div class="board">

    <table class="showw">
      <tr>
        <th class='stat'> Status</th>
        <th>Session's date</th>
        <th>Description</th>
        <th>Resources</th>
        <th class='ulfile'>Upload a file</th>
      </tr>

      <tr>
        <% @sessions.sort_by(&:start_date).each do |session| %>
        <% if session.start_date > DateTime.now %>
          <td class="inc"> <%= session.status = "Incoming" %></td>
          <% elsif session.start_date == DateTime.now %>
          <td class="today"> <%= session.status = "Today" %></td>
          <% else %>
          <td class ="passed"> <%= session.status = "Passed" %></td>
        <% end %>
          <td> <%= session.start_date.strftime('%d-%b-%Y')%> - <%= session.start_time.to_formatted_s(:time)%> </td>

          <td class ="searched"><%= session.name %> </td>
          <td class="dl"><a href="http://exo7.emath.fr/cours/livre-algebre-1.pdf" target = "blank"download>
            <i class="fa-solid fa-download" width="50px"></i>
              </a></td>
          <td><%= link_to edit_student_course_path(@course) do %>
             <i class="fa-solid fa-cloud-arrow-up"></i>
             <% end %> </td>
      </tr>
      <% end %>
    </table>
  </div>

  <div class="rgtside">

    <div class="cool">
      <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1665171176/Studeasy/Sans_titre_-_2022-10-07T213223.850_ixyyzb.png', width:'270' %>

    </div>

    <div class="buttonz">
      <div class="linksession">
        <%= link_to "Courses", courses_path, class: "backbtn" %>
        <%= link_to "Results" , result_path(@course.id) %> <%= link_to "Chat" , Chatroom.find_by(name: 'Algebra') %>
      </div>
      <%# <div class="linksession">

      </div> %>
    </div>





  </div>


</div>

<br>
<br>





   <%# =========================== CODE BASE =============== %>

<%#
<% @course.sessions.each do |session| %>
  <%# <div class="courses-sessions">
    <br>

      <li><%#= link_to "session's date", session_path(session.id) = session.id %>
<%#
      <br>
      <li> Name: <%= session.name %>
      <%# <li> Start Date: <%= session.start_date %>
      <%# <li> End Date: <%= session.end_date %>
      <%# <li> Status: <%= session.status %>
    <%# <br>
<%#
    <li><%#= link_to "Documents", session %>

  <%# </div> %>
<%# <% end %>

<%# <h3> Your personnal documents</h3> %>
<%# <%= @course.file.key, height: 300, width: 400, crop: :fill %>

<%# <h3> Add a personnal document</h3>

<%= link_to "Upload file", edit_student_course_path(@course) %>


 <%# =================CODE TABLEAU BASE =========================== %>

        <%# <tr>
          <td>15/09/22</td>
          <td>Functions part 2</td>
          <td> Use the basic functions</td>
          <td>M. Watson</td>
          <td><a href="https://res.cloudinary.com/dhxefoe7j/image/upload/v1663240085/Studeasy/pexels-max-fischer-5212316_ixkpyx.jpg" download>
            <img src="https://res.cloudinary.com/dhxefoe7j/image/upload/v1663240085/Studeasy/pexels-max-fischer-5212316_ixkpyx.jpg" width="40px" alt="Lesson 3">
              </a></td>
          <td><input type="file"
            id="file" name="file"
            accept="image/png, image/jpeg"></td>
        </tr>

        <tr>
          <td>19/09/22</td>
          <td>Probabilities part 1/3</td>
          <td> understand the basis</td>
          <td>Ms Johnson</td>
          <td><a href="https://res.cloudinary.com/dhxefoe7j/image/upload/v1663240291/Studeasy/pexels-vanessa-garcia-6325944_qzimf9.jpg" download>
            <img src="https://res.cloudinary.com/dhxefoe7j/image/upload/v1663240291/Studeasy/pexels-vanessa-garcia-6325944_qzimf9.jpg" width="40px" alt="Lesson 3">
              </a></td>
          <td><input type="file"
            id="file" name="file"
            accept="image/png, image/jpeg"></td>
        </tr>

        <tr>
          <td>20/09/22</td>
          <td>Probabilities part 2/3</td>
          <td> use basic probabilities</td>
          <td>Ms Johnson</td>
          <td><a href="https://res.cloudinary.com/dhxefoe7j/image/upload/v1663240075/Studeasy/pexels-katerina-holmes-5905475_psy0d7.jpg" download>
            <img src="https://res.cloudinary.com/dhxefoe7j/image/upload/v1663240075/Studeasy/pexels-katerina-holmes-5905475_psy0d7.jpg" width="40px" alt="Lesson 3">
              </a></td>
          <td><input type="file"
            id="file" name="file"
            accept="image/png, image/jpeg"></td>
        </tr>

        <tr>
          <td>22/09/22</td>
          <td>Probabilities part 3/3</td>
          <td> advanced prob</td>
          <td>M. White</td>
          <td><a href="https://res.cloudinary.com/dhxefoe7j/image/upload/v1663240074/Studeasy/pexels-jeswin-thomas-3781338_shttvz.jpg" download>
            <img src="https://res.cloudinary.com/dhxefoe7j/image/upload/v1663240074/Studeasy/pexels-jeswin-thomas-3781338_shttvz.jpg" width="40px" alt="Lesson 3">
              </a></td>
          <td><input type="file"
            id="file" name="file"
            accept="image/png, image/jpeg"></td>
        </tr> %>